language: node_js
node_js:
- 10
branches:
  only:
  - master
script:
-
env:
  - NODE_ENV=development
deploy:
  provider: firebase
  project: wirvsvirus-coronaq-development
  token:
    secure: llHpxJ8OxPld7TqNM5UUCHeqWRsABRNVF9kOicqbQEndomCYIhg/E8pTB37WF1YCSV2tlS0R6Jlmn62dk2XwstEsTBK3Qp64NXmM5Yflqa6QepWvQV4RDah2P2flIarWa0ZAkaPim+aMu7//YuE2jyWvkLyTQKMuXox0G9InXpHYJ5cPXDOImcgnmsBcm1aJTVqPHfDIbaT4Idvg1ymt/y8AYv6AlbWPXxJZ05a28oobm/uaiw5oeqvlki7Amc4SsFwYiCcK/YF5HYhTHXa0mHydeDyt5xtIuQkwWpgLfxySwUKniCRloe09JGo/TEWRLiZTF+GzY1j2L7aE8CtByqUwInCHkNMyFePeEcalgZvrX8w6xQyiP0Ri0RmnJjRqbibiIB5QTxTYS5/fmTldPtESdNl0RmtzzJxdgDzw9JMpq0phbvIrozQgQWpvJtaqbiGXmUoWdGjM8v9gbqrxBAmnrvhZ1xL0fJXADTYZD3YjjQphp00wRx3dkyEn8d8GL58V0qBFY/tIb1gienlUmYyfrNM5XfdhT2L16cDFi+V7BjGkaPWA179mPeC1SU378zTPqGMVWfUp5AXEJ3h4P/qBJMXghYykvGZQ4XKtN3TO4WtxeW4gjOQpC8HXyoeZSbBla7VN2iK6fDNonee0tZZhG6sEbsBUMDv+oRhDrc0=
